spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zhangxj@163.com
    url: jdbc:mysql://localhost:3306/shopsystem?characterEncoding=utf-8

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.max.maxmall.entity